{% extends 'base.html' %}

{% block title %}Internal Server Error{% endblock %}

{% block content %}

<div id="message-retrying" style="display: none;">

  <div style="text-align: center;padding-top: 3em;">

    <img src="/static/img/wait.gif" style="padding: 1em;"/>

    <h1 style="text-align: center; padding: 0 3em 3em 3em;">Wait a moment...</h1>

  </div>

</div>

<div id="message-error">

<h1>Internal Server Error</h1>

We're sorry, an internal error occurred in our software and we're unable to
process your request.  Please try again later, or contact us for assistance.
A report of the error has been sent to us for investigation.

<p>
  If you'd like, you can <a class="try_again_link" href="">try again now</a>.
</p>

{% if unhandled_500 %}
<p>This error may be caused by a misconfiguration or temporary outage in our systems.</p>{% endif %}

<p>If you contact us about this error, please note that the failure was on:<br><span id="errorurl" style="font-family:'Courier',monospace;"></span></p>
<script>(function(){
var x = document.getElementById('errorurl');
if (x){x.innerHTML = window.location.href;}
})();</script>
</div>

{% endblock %}


{% block bodyendscript %}
<script type="text/javascript">
_gaq.push(['_trackEvent', 'Errors', '{% if unhandled_500 %}Unhandled server error'{% else %}Caught server error{% endif %}', 'URL: '+document.location]);

// hide both messages by default if JS supported, to reduce chance of flashing confusing messages
document.getElementById("message-retrying").style.display = "none";
document.getElementById("message-error").style.display = "none";
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js">1;</script>
<script type="text/javascript">
{% include 'js/error_retry.js' %}
</script>
{% endblock %}
